-- MySQL Script generated by MySQL Workbench
-- Sun Mar  1 13:51:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publishers` (
  `id_publisher` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_publisher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`authors` (
  `id_author` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_author`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `id_publisher` INT NOT NULL,
  `id_genre` INT NOT NULL,
  `synopsis` TEXT NULL,
  PRIMARY KEY (`id_book`),
  UNIQUE INDEX `ISBN_UNIQUE` (`isbn` ASC) VISIBLE,
  INDEX `fk_Libros_Editoriales1_idx` (`id_publisher` ASC) VISIBLE,
  INDEX `fk_Libros_Generos1_idx` (`id_genre` ASC) VISIBLE,
  CONSTRAINT `fk_books_publishers`
    FOREIGN KEY (`id_publisher`)
    REFERENCES `mydb`.`publishers` (`id_publisher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_genres`
    FOREIGN KEY (`id_genre`)
    REFERENCES `mydb`.`genres` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`book_authors` (
  `id_author` INT NOT NULL,
  `id_book` INT NOT NULL,
  INDEX `fk_Autores_has_Libros_Autores1_idx` (`id_author` ASC) VISIBLE,
  INDEX `fk_Libro_autor_Libros_idx` (`id_book` ASC) VISIBLE,
  PRIMARY KEY (`id_author`, `id_book`),
  CONSTRAINT `fk_book_author_authors`
    FOREIGN KEY (`id_author`)
    REFERENCES `mydb`.`authors` (`id_author`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_author_books`
    FOREIGN KEY (`id_book`)
    REFERENCES `mydb`.`books` (`id_book`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_types` (
  `id_user_type` INT NOT NULL AUTO_INCREMENT,
  `name` ENUM('Docente', 'Alumno', 'Usuario Externo') NOT NULL,
  PRIMARY KEY (`id_user_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`addresses` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(60) NOT NULL,
  `ext_num` VARCHAR(10) NOT NULL,
  `int_num` VARCHAR(10) NULL,
  `neighborhood` VARCHAR(50) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `name` ENUM('Administrador', 'Bibliotecario', 'Usuario') NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `id_user_type` INT NOT NULL,
  `id_address` INT NOT NULL,
  `id_role` INT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `Correo_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Usuarios_Tipo_usuario1_idx` (`id_user_type` ASC) VISIBLE,
  INDEX `fk_Usuarios_Domicilio1_idx` (`id_address` ASC) VISIBLE,
  INDEX `fk_Usuarios_Roles1_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_users_user_types`
    FOREIGN KEY (`id_user_type`)
    REFERENCES `mydb`.`user_types` (`id_user_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_addresses`
    FOREIGN KEY (`id_address`)
    REFERENCES `mydb`.`addresses` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`id_role`)
    REFERENCES `mydb`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bookings` (
  `id_booking` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_book` INT NOT NULL,
  `booking_date` DATE NOT NULL,
  `availability_alert` TINYINT(1) NOT NULL DEFAULT 0,
  `status` ENUM('En Espera', 'Listo para entrega', 'Cancelado') NOT NULL,
  PRIMARY KEY (`id_booking`),
  INDEX `fk_Reservas_Libros1_idx` (`id_book` ASC) VISIBLE,
  INDEX `fk_Reservas_Usuarios1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_books`
    FOREIGN KEY (`id_book`)
    REFERENCES `mydb`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`logs` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `table_name` VARCHAR(45) NOT NULL,
  `action` ENUM('Crear', 'Actualizar', 'Consultar', 'Eliminar') NOT NULL,
  `old_data` JSON NULL,
  `new_data` JSON NULL,
  `movement_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log`),
  INDEX `fk_Accesos_Usuarios1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_logs_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id_permission` INT NOT NULL AUTO_INCREMENT,
  `access` VARCHAR(45) NOT NULL,
  `module` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_permission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles_permissions` (
  `id_role` INT NOT NULL,
  `id_permission` INT NOT NULL,
  INDEX `fk_Roles_has_Permisos_Permisos1_idx` (`id_permission` ASC) VISIBLE,
  INDEX `fk_Roles_has_Permisos_Roles1_idx` (`id_role` ASC) VISIBLE,
  PRIMARY KEY (`id_permission`, `id_role`),
  CONSTRAINT `fk_roles_has_permissions_roles`
    FOREIGN KEY (`id_role`)
    REFERENCES `mydb`.`roles` (`id_role`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_roles_has_permissions_permissions`
    FOREIGN KEY (`id_permission`)
    REFERENCES `mydb`.`permissions` (`id_permission`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`copies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`copies` (
  `id_copy` INT NOT NULL AUTO_INCREMENT,
  `id_book` INT NOT NULL,
  `year` YEAR NOT NULL,
  `edition` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NULL,
  `status` ENUM('Disponible', 'Prestado', 'En reparación', 'No disponible', 'Dañado') NOT NULL,
  `notes` VARCHAR(150) NULL,
  PRIMARY KEY (`id_copy`),
  INDEX `fk_Ejemplares_Libros1_idx` (`id_book` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_copies_books`
    FOREIGN KEY (`id_book`)
    REFERENCES `mydb`.`books` (`id_book`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loans` (
  `id_loan` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_booking` INT NULL,
  `id_copy` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `return_deadline` DATE NOT NULL,
  `status` ENUM('Activo', 'Finalizado', 'Con adeudo', 'Cancelado') NOT NULL,
  PRIMARY KEY (`id_loan`),
  INDEX `fk_Prestamos_Usuarios1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_Prestamos_Reservas1_idx` (`id_booking` ASC) VISIBLE,
  INDEX `fk_Prestamos_Ejemplares1_idx` (`id_copy` ASC) VISIBLE,
  CONSTRAINT `fk_loans_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loans_bookings`
    FOREIGN KEY (`id_booking`)
    REFERENCES `mydb`.`bookings` (`id_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loans_copies`
    FOREIGN KEY (`id_copy`)
    REFERENCES `mydb`.`copies` (`id_copy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`returns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`returns` (
  `id_return` INT NOT NULL AUTO_INCREMENT,
  `id_loan` INT NOT NULL,
  `return_date` DATE NOT NULL,
  `notes` VARCHAR(100) NULL,
  PRIMARY KEY (`id_return`),
  INDEX `fk_Devoluciones_Prestamos1_idx` (`id_loan` ASC) VISIBLE,
  UNIQUE INDEX `id_prestamo_UNIQUE` (`id_loan` ASC) VISIBLE,
  CONSTRAINT `fk_returns_loans`
    FOREIGN KEY (`id_loan`)
    REFERENCES `mydb`.`loans` (`id_loan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fines` (
  `id_fine` INT NOT NULL AUTO_INCREMENT,
  `id_return` INT NOT NULL,
  `fine_date` DATE NOT NULL,
  `amount` DECIMAL(5,2) NOT NULL,
  `status` ENUM('Pagada', 'Pendiente', 'Cancelada') NOT NULL,
  `payment_date` DATE NULL,
  PRIMARY KEY (`id_fine`),
  INDEX `fk_Multas_Devoluciones1_idx` (`id_return` ASC) VISIBLE,
  CONSTRAINT `fk_fines_returns`
    FOREIGN KEY (`id_return`)
    REFERENCES `mydb`.`returns` (`id_return`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login_history` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `login_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('Exitoso', 'Fallido') NOT NULL,
  PRIMARY KEY (`id_login`),
  INDEX `fk_login_history_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_login_history_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
